// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHF3w2oqSVW1Duw-AQ1QIY5USXkC-k4dQ',
    appId: '1:567397044370:web:dbcb3665e66468faa5964b',
    messagingSenderId: '567397044370',
    projectId: 'expense-tracker-6ac01',
    authDomain: 'expense-tracker-6ac01.firebaseapp.com',
    storageBucket: 'expense-tracker-6ac01.firebasestorage.app',
    measurementId: 'G-Q62YF979G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZAL68qTy1p-J720bGOW9DXshmBWhcJY',
    appId: '1:567397044370:android:85abab00f5c1db19a5964b',
    messagingSenderId: '567397044370',
    projectId: 'expense-tracker-6ac01',
    storageBucket: 'expense-tracker-6ac01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPN_9SDJYqLdLtmmV54hjLjmsWItF0bQ',
    appId: '1:567397044370:ios:d505cb52b7925ea5a5964b',
    messagingSenderId: '567397044370',
    projectId: 'expense-tracker-6ac01',
    storageBucket: 'expense-tracker-6ac01.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZPN_9SDJYqLdLtmmV54hjLjmsWItF0bQ',
    appId: '1:567397044370:ios:d505cb52b7925ea5a5964b',
    messagingSenderId: '567397044370',
    projectId: 'expense-tracker-6ac01',
    storageBucket: 'expense-tracker-6ac01.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHF3w2oqSVW1Duw-AQ1QIY5USXkC-k4dQ',
    appId: '1:567397044370:web:6a1b95fd4415c031a5964b',
    messagingSenderId: '567397044370',
    projectId: 'expense-tracker-6ac01',
    authDomain: 'expense-tracker-6ac01.firebaseapp.com',
    storageBucket: 'expense-tracker-6ac01.firebasestorage.app',
    measurementId: 'G-DFJQ4R7NPQ',
  );
}
